spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vollmed_api
    driver-class-name: com.mysql.cj.jdbc.Driver
    database: MYSQL
    username: everton
    password: rocha123

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
      sort:
        sort-parameter: ordem

  output:
    ansi:
      enabled: always

  security:
    user:
      name: everton
      password: 123

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:123456}